import { db } from "./index";
import { imageTypes } from "./schema";

const IMAGE_TYPES_SEED = [
  // Category A — Admin / Branding (500 KB max)
  {
    category: "admin",
    typeKey: "logo_topo",
    displayName: "Logo Topo (Header)",
    description: "Logo exibida no topo da plataforma desktop",
    width: null,
    height: null,
    aspectRatio: "variable",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: 200,
    previewContext: "desktop_header",
    services: ["LMS Web"],
  },
  {
    category: "admin",
    typeKey: "logo_relatorios",
    displayName: "Logo Relatórios",
    description: "Logo usada em cabeçalhos de relatórios PDF",
    width: 650,
    height: 200,
    aspectRatio: "3.25:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "email_header",
    services: ["LMS Web"],
  },
  {
    category: "admin",
    typeKey: "fundo_login",
    displayName: "Fundo Login Desktop",
    description: "Imagem de fundo da tela de login desktop",
    width: 1600,
    height: 900,
    aspectRatio: "16:9",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "desktop_login",
    services: ["LMS Web"],
  },
  {
    category: "admin",
    typeKey: "fundo_login_mobile",
    displayName: "Fundo Login Mobile",
    description: "Imagem de fundo da tela de login mobile",
    width: 375,
    height: 820,
    aspectRatio: "~9:20",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "phone_login",
    services: ["App Mobile"],
  },
  {
    category: "admin",
    typeKey: "icone_pilula",
    displayName: "Ícone Notificação Pílula",
    description: "Ícone usado em notificações de pílulas de conhecimento",
    width: 72,
    height: 72,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "content_viewer",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "admin",
    typeKey: "favicon",
    displayName: "Favicon",
    description: "Ícone exibido na aba do navegador",
    width: 128,
    height: 128,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "browser_tab",
    services: ["LMS Web"],
  },
  {
    category: "admin",
    typeKey: "testeira_email",
    displayName: "Testeira E-mail",
    description: "Imagem de cabeçalho de emails da plataforma",
    width: 600,
    height: 100,
    aspectRatio: "6:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "email_header",
    services: ["E-mail"],
  },
  {
    category: "admin",
    typeKey: "logo_app",
    displayName: "Logo Interno App",
    description: "Logo exibida no topo do app mobile",
    width: null,
    height: null,
    aspectRatio: "variable",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: 200,
    previewContext: "phone_header",
    services: ["App Mobile"],
  },
  {
    category: "admin",
    typeKey: "logo_dispersao",
    displayName: "Logo Mapa Dispersão",
    description: "Logo minúscula usada como marcador no mapa de dispersão",
    width: 27,
    height: 27,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "map_marker",
    services: ["Gestão RH"],
  },
  // Category B — Content / Workspace (10 MB max)
  {
    category: "content",
    typeKey: "conteudo_imagem",
    displayName: "Imagem de Conteúdo",
    description: "Imagem usada em conteúdos educacionais",
    width: 1920,
    height: 1080,
    aspectRatio: "16:9",
    maxFileSizeKb: 10240,
    allowedFormats: ["png", "jpeg", "gif"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "content_viewer",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "content",
    typeKey: "capa_workspace",
    displayName: "Capa Workspace",
    description: "Imagem para o card do canal/workspace (recomendado 300×300 px)",
    width: 300,
    height: 300,
    aspectRatio: "1:1",
    maxFileSizeKb: 10240,
    allowedFormats: ["png", "jpeg", "gif"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "workspace_card",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "content",
    typeKey: "fundo_workspace",
    displayName: "Fundo Workspace",
    description: "Imagem de fundo para o canal/workspace (recomendado 1920×1080 px)",
    width: 1920,
    height: 1080,
    aspectRatio: "16:9",
    maxFileSizeKb: 10240,
    allowedFormats: ["png", "jpeg", "gif"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "workspace_details",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "content",
    typeKey: "icone_curso",
    displayName: "Ícone de Curso",
    description: "Ícone quadrado do curso — aceita APENAS JPG",
    width: 256,
    height: 256,
    aspectRatio: "1:1",
    maxFileSizeKb: 10240,
    allowedFormats: ["jpg"],
    recommendedFormat: "jpg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "course_card",
    services: ["LMS Web", "App Mobile"],
  },
  // Category C — User (1 MB max)
  {
    category: "user",
    typeKey: "foto_aluno",
    displayName: "Foto de Perfil",
    description: "Foto do perfil do aluno/usuário",
    width: 256,
    height: 256,
    aspectRatio: "1:1",
    maxFileSizeKb: 1024,
    allowedFormats: ["jpg", "png", "jpeg"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "profile_avatar",
    services: ["LMS Web", "App Mobile"],
  },
  // Category D — Gamification (500 KB max)
  {
    category: "gamification",
    typeKey: "badge_conquista",
    displayName: "Badge de Conquista",
    description: "Badge circular exibido no perfil do aluno ao completar um marco",
    width: 128,
    height: 128,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "gamification_badge",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "gamification",
    typeKey: "medalha_ranking",
    displayName: "Medalha de Ranking",
    description: "Medalha exibida no ranking de gamificação (ouro, prata, bronze)",
    width: 96,
    height: 96,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "gamification_ranking",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "gamification",
    typeKey: "icone_recompensa",
    displayName: "Ícone de Recompensa",
    description: "Ícone de item na loja virtual de recompensas",
    width: 200,
    height: 200,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "png",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "gamification_store",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "gamification",
    typeKey: "banner_campanha",
    displayName: "Banner de Campanha",
    description: "Banner exibido no topo da seção de gamificação para campanhas especiais",
    width: 1200,
    height: 300,
    aspectRatio: "4:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png", "jpeg"],
    recommendedFormat: "jpeg",
    requiresTransparency: false,
    minWidth: null,
    previewContext: "gamification_campaign",
    services: ["LMS Web", "App Mobile"],
  },
  {
    category: "gamification",
    typeKey: "avatar_personagem",
    displayName: "Avatar de Personagem",
    description: "Avatar/mascote usado em interações gamificadas",
    width: 256,
    height: 256,
    aspectRatio: "1:1",
    maxFileSizeKb: 500,
    allowedFormats: ["png"],
    recommendedFormat: "png",
    requiresTransparency: true,
    minWidth: null,
    previewContext: "gamification_avatar",
    services: ["LMS Web", "App Mobile"],
  },
];

async function seed() {
  console.log("🌱 Seeding image types...");

  for (const type of IMAGE_TYPES_SEED) {
    await db
      .insert(imageTypes)
      .values(type)
      .onConflictDoUpdate({
        target: imageTypes.typeKey,
        set: {
          displayName: type.displayName,
          description: type.description,
          width: type.width,
          height: type.height,
          aspectRatio: type.aspectRatio,
          maxFileSizeKb: type.maxFileSizeKb,
          allowedFormats: type.allowedFormats,
          recommendedFormat: type.recommendedFormat,
          requiresTransparency: type.requiresTransparency,
          minWidth: type.minWidth,
          previewContext: type.previewContext,
          services: type.services,
          updatedAt: new Date(),
        },
      });
    console.log(`  ✓ ${type.typeKey} (${type.displayName})`);
  }

  console.log(`\n✅ Seeded ${IMAGE_TYPES_SEED.length} image types.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
